[package]
name = "kframework"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
clap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
pyo3 = { workspace = true, optional = true }

[dev-dependencies]
indoc = { workspace = true }

[features]
python = ["dep:pyo3"]
