ARG K_VERSION=7.1.241
ARG RUST_TOOLCHAIN=1.85.0

FROM runtimeverificationinc/kframework-k:ubuntu-jammy-${K_VERSION} AS semantics

WORKDIR /opt/imp-semantics
COPY examples/fuzzer/k-semantics .
RUN kompile --llvm-kompile-type c fuzz.k

FROM rust:${RUST_TOOLCHAIN}

COPY --from=semantics /opt/imp-semantics/fuzz-kompiled/interpreter.so /usr/lib
RUN apt-get update && apt-get install --yes build-essential binutils-dev libclang-dev libunwind-dev libblocksruntime-dev liblzma-dev
RUN cargo install honggfuzz

ARG USER=user
ARG GROUP=$USER
ARG USER_ID=1000
ARG GROUP_ID=$USER_ID

RUN groupadd -g $GROUP_ID $GROUP && useradd -m -u $USER_ID -s /bin/sh -g $GROUP $USER

USER $USER:$GROUP
