name: 'Test PR'
on:
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    name: 'Build and Test Project'
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out code'
        uses: actions/checkout@v4
      - name: 'Build and test'
        run: make

  build-ffi-and-fuzz:
    name: 'Build with the FFI and run the fuzzing example'
    runs-on: [self-hosted, linux, normal]
    steps:
      - name: 'Check out code'
        uses: actions/checkout@v4
      - name: 'Set up Docker'
        uses: ./.github/actions/with-docker
        with:
          container-name: kframework-rs-fuzz-${{ github.sha }}
          dockerfile: Dockerfile.fuzz
      - name: 'Build and test'
        run: |
          export HFUZZ_RUN_ARGS="--verbose --logfile log.txt --run_time 60"
          docker exec                                \
            --env HFUZZ_RUN_ARGS="${HFUZZ_RUN_ARGS}" \
            --workdir /home/user/examples/fuzzer     \
            kframework-rs-fuzz-${GITHUB_SHA}         \
            cargo hfuzz run fuzzer
          echo "Final lines of hfuzz output:"
          docker exec                                \
            --env HFUZZ_RUN_ARGS="${HFUZZ_RUN_ARGS}" \
            --workdir /home/user/examples/fuzzer     \
            kframework-rs-fuzz-${GITHUB_SHA}         \
            tail log.txt
      - name: 'Tear down Docker'
        if: always()
        run: |
          docker stop --time=0 kframework-rs-fuzz-${GITHUB_SHA}
